#!/usr/bin/env python

from tilemapgen import commands
import pyrallis
import sys

def main():
    command = sys.argv[1]
    commands.execute(command, sys.argv[2:])

if __name__ == '__main__':
    main()