#!/usr/bin/env python

from tilemapgen import commands
from tilemapgen.logging import logger
import sys


def main():
    command = sys.argv[1]
    commands.execute(command, sys.argv[2:])

if __name__ == '__main__':
    main()